# Generated by Django 4.2.4 on 2023-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_dict_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='values',
            field=models.CharField(max_length=6000),
        ),
    ]
